---
- hosts: localhost
  connection: local 
  gather_facts: false

  handlers:
    - name: reload systemd
      systemd:
        state: restarted
        daemon_reload: yes
        name: docker
      become: true
      ignore_errors: True
      
  tasks:
    - name: Gather restrictive facts
      setup:
        gather_subset:
        - 'min'

    - name: Update packages
      apt: 
        update_cache: yes
        cache_valid_time: 3600
      become: true
      when: ansible_os_family == "Debian"

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true
      when: ansible_os_family == "Debian"

    - name: Add Docker Repository
      apt_repository:
        repo: "deb https://download.docker.com/linux/ubuntu  {{ ubuntu_distro | default('jammy') }} stable"
        state: present
      become: true
      when: ansible_os_family == "Debian"

    - name: Install Docker
      package:
        name: 
          - docker-ce
        state: present
      become: true

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      ignore_errors: True
      become: true

    - name: Criar diretorios do docker
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      become: true
      loop:
        - /etc/docker
        - /etc/systemd/system/docker.service.d

    - name: Copiar arquivo de configuração do docker
      copy:
        mode: 0644
        src: ./resources/daemon.json
        dest: /etc/docker/daemon.json
      become: true
      notify: reload systemd

    - name: Verifica arquivo de configuração docker para usuário
      stat:
        path: ~/.docker/config.json
      register: docker_cfg_result

    - name: Add user {{ ansible_user_id }} to docker group
      user: 
        name={{ ansible_user_id }}
        groups=docker
        append=yes
      become: true
