---
- hosts: localhost
  connection: local 
  become: true

  tasks:  
    - name: Check if dbeaver-ce is installed
      command: dpkg-query -W dbeaver-ce
      register: dbeaver_deb_pkg
      failed_when: dbeaver_deb_pkg.rc > 1
      changed_when: dbeaver_deb_pkg.rc == 1
      
    - name: Download dbeaver-ce
      get_url: 
        url="https://dbeaver.io/files/dbeaver-ce_latest_amd64.deb"
        dest="/tmp/dbeaver-ce_latest_amd64.deb"
      when: dbeaver_deb_pkg.rc == 1

    - name: Install dbeaver-ce
      apt: deb="/tmp/dbeaver-ce_latest_amd64.deb"
      become: true
      when: dbeaver_deb_pkg.rc == 1

    - name: Remove dbeaver-ce install package
      file:
        path: /tmp/dbeaver-ce_latest_amd64.deb
        state: absent
      when: dbeaver_deb_pkg.rc == 1  