---
- hosts: localhost
  connection: local 
  become: true
  gather_facts: false

  tasks:
    - name: Add inkscape repo
      apt_repository:
        repo: 'ppa:inkscape.dev/stable'
        codename: "{{ ubuntu_distro | default('jammy') }}"

    - name: Install inkscape
      apt:
        update_cache: yes
        name: inkscape
        state: latest
