---
- hosts: localhost
  connection: local 
  become: true

  tasks:
    - name: Check if mongodb is installed
      command: dpkg-query -W mongodb-mongosh
      register: mongodb_deb_pkg
      failed_when: mongodb_deb_pkg.rc > 1
      changed_when: mongodb_deb_pkg.rc == 1
  
    - name: Get mongodb key
      get_url:
        url:  https://www.mongodb.org/static/pgp/server-{{ mongodb_version | default('6.0') }}.asc
        dest: /tmp/mongo_public.asc
      when: mongodb_deb_pkg.rc == 1

    - name: Create mongodb gpg key 
      command: gpg --batch --yes -o /usr/share/keyrings/mongodb-keyring.gpg --dearmor /tmp/mongo_public.asc
      register: gpg_output
      when: mongodb_deb_pkg.rc == 1

    - name: Remove mongodb temp key
      file:
        path: "/tmp/mongo_public.asc"
        state: absent
      when: mongodb_deb_pkg.rc == 1 and gpg_output.rc == 0
 
    - name: Add nordvpn repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/mongodb-keyring.gpg] https://repo.mongodb.org/apt/ubuntu {{ ubuntu_distro | default('jammy') }}/mongodb-org/{{ mongodb_version | default('6.0') }} multiverse"
        state: present
      when: mongodb_deb_pkg.rc == 1 and gpg_output.rc == 0

    - name: Install mongodb tools
      apt:
        update_cache: yes
        pkg: 
          - mongodb-mongosh
          - mongodb-org-tools
          - mongodb-org-database-tools-extra
          - mongodb-database-tools
      when: mongodb_deb_pkg.rc == 1

    - name: Check if mongodb-compass is installed
      command: dpkg-query -W mongodb-compass
      register: compass_deb_pkg
      failed_when: compass_deb_pkg.rc > 1
      changed_when: compass_deb_pkg.rc == 1
      
    #TODO Try to discover the latest version....
    - name: Download mongodb-compass
      get_url: 
        url="https://downloads.mongodb.com/compass/mongodb-compass_{{ mongo_compass_version | default('1.34.2') }}_amd64.deb"
        dest="/tmp/mongodb-compass.deb"
      when: compass_deb_pkg.rc == 1

    - name: Install mongodb-compass
      apt: deb="/tmp/mongodb-compass.deb"
      become: true
      when: compass_deb_pkg.rc == 1

    - name: Remove mongodb-compass install package
      file:
        path: /tmp/mongodb-compass.deb
        state: absent
      when: compass_deb_pkg.rc == 1  
